#-----------------------------------------------------------------
# auto loaded
#-----------------------------------------------------------------

[[plugins]]
repository = 'Shougo/vimproc.vim'

    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    others = 'make'

[[plugins]]
repository = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

[[plugins]]
repository = 'blindFS/miscellaneous'
lazy = 0

[[plugins]]
repository = 'Shougo/tabpagebuffer.vim'
lazy = 0

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'junegunn/vim-peekaboo'

#-----------------------------------------------------------------
# eyecandy
#-----------------------------------------------------------------

[[plugins]]
repository = 'bling/vim-airline'

[[plugins]]
repository = 'ryanoasis/vim-devicons'
gui = 1

[[plugins]]
repository = 'blindFS/Rainbow-Parentheses-Improved-and2'

[[plugins]]
repository = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repository = 'mhinz/vim-signify'

[[plugins]]
repository = 'blueyed/vim-diminactive'
