let g:vimfiler_force_overwrite_statusline = 0
let g:vimfiler_as_default_explorer        = 1
let g:vimfiler_tree_leaf_icon             = ' '
let g:vimfiler_tree_opened_icon           = '▾'
let g:vimfiler_tree_closed_icon           = '▸'
let g:vimfiler_file_icon                  = '-'
let g:vimfiler_marked_file_icon           = '*'
let g:vimfiler_ignore_pattern             = '^\%(.git\|.DS_Store\)$'
let g:vimfiler_data_directory             = $HOME.'/tmp/vimfiler'
